# Generated by Django 5.0.7 on 2024-09-18 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_user_birth_date_alter_user_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="cook_time",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="portions",
        ),
    ]
