# Generated by Django 5.0.7 on 2024-09-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_remove_recipe_cook_time_remove_recipe_portions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredients",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingridients",
        ),
        migrations.RemoveField(
            model_name="queryhistory",
            name="user",
        ),
        migrations.RemoveField(
            model_name="recipeingredients",
            name="recipe",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(default=""),
        ),
        migrations.DeleteModel(
            name="Ingredients",
        ),
        migrations.DeleteModel(
            name="QueryHistory",
        ),
        migrations.DeleteModel(
            name="RecipeIngredients",
        ),
    ]
